# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f75f4889b14e34ebecf99a69dcf634e211c1040c9851f08cdfb52196af07cafcca3536e38b618623b805ceac713b7ad0b2f81b804ef074a1ef1e6634bfc59257

test:
  secret_key_base: df2b149533fd59184b518253ff21d64cb7578414ef5d949558c26d52a26cfbdf033411bab112a7219b46637cf1c7034e6bab80ca4c4e4c2d07da608ac55899fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
